### ISSUE TITLE
Docker facade never healthy

### ISSUE THREAD

**Issue by buggtb** [mrsimonemms/gitpod-self-hosted#16]
### Bug description

```
Request createWorkspace failed with message: 13 INTERNAL: cannot resolve workspace image: failed to do request: Head "https://registry.gitpod.spicpod.tech/v2/workspace-images/manifests/2e37fc8e3d3884eca309093358f96b5062dbee61df27337b4bf41e0d18ac78e0": dial tcp: lookup registry.gitpod.spicpod.tech on 10.43.0.10:53: no such host

Unknown Error: { "code": -32603 }
```

### Steps to reproduce

if i told you this was the last issue, it'd probably be a lie, but its close, trying to launch a workspace but the registry seems to be sad and gitpod ui responds saying there's on such host.

annnnnny clue at all? is it supposed to be an internal loop back or is it really supposed to route through the loadbalancer? I can't tell

### Expected behavior

shouldn't crash.

**Comment by mrsimonemms** [comment]
It looks like something to do with the load balancer

````
 dial tcp: lookup registry.gitpod.spicpod.tech on 10.43.0.10:53: no such host
````

Questions to check:
1. Have you got `gitpod.spicpod.tech`, `*.gitpod.spicpod.tech` and `*.ws.gitpod.spicpod.tech` set up in the DNS? They should all point through to the same A/CNAME record (I'm getting a fail when I do an `nslookup`, so I think it's this)
2. Have you got the TLS cert set on the same three domains?

**Comment by buggtb** [comment]
What a knob, I had "fix the DNS properly before handing the terraform over for testing" on my list 😫

**Comment by mrsimonemms** [comment]
I know that pain greatly

**Comment by mrsimonemms** [comment]
I'm loving the bugs that are getting closed themselves 😄

**Comment by buggtb** [comment]
Part of me says I shouldn't file them, then the other part says if other people go through this and hit similar stuff, at least there's some trail of moronic actions.

**Comment by mrsimonemms** [comment]
Yeah, you definitely should. This `-32603` message is the stupidest/most unhelpful one ever. It was the issue we'd have raised the most often, simply because the nice error message doesn't bubble up to the webpage
