### ISSUE TITLE
401 on dockerhub fetch

### ISSUE THREAD

**Issue by buggtb** [mrsimonemms/gitpod-self-hosted#17]
### Bug description

`│ 2023/02/16 22:27:22 [DEBUG] GET https://registry-1.docker.io/v2/gitpod/workspace-full/blobs/sha256:767f03219b5ba311930c5b5410acc74f04beb6d1d642e85adb0d78605c418a3f (status: 401): retrying in 1s (3 left)                                                                                                                                                                             ││ 2023/02/16 22:27:26 [DEBUG] PUT https://registry.gitpod.spicpod.tech/v2/workspace-images/blobs/uploads/0e20a1b8-8285-4ac4-aff2-886fb1d98b38?_state=yux6X-yNucK6yrNuCtfl7P1WpPJecmY2_miqtNWiIbF7Ik5hbWUiOiJ3b3Jrc3BhY2UtaW1hZ2VzIiwiVVVJRCI6IjBlMjBhMWI4LTgyODUtNGFjNC1hZmYyLTg4NmZiMWQ5OGIzOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wMi0xNlQyMjoyNzoyMC42NDIzODk5ODFaIn0%3D&digest=s ││ {"file":"auth.go:30","func":"func1","host":"registry.gitpod.spicpod.tech","level":"info","message":"authorizing registry access","serviceContext":{"service":"bob","version":""},"severity":"INFO","time":"2023-02`

### Steps to reproduce

I assume this is trying to get an image from the gitpod dockerhub repo and stick it in the cluster repo.

Its 401ing cause of their login permission shit I guess. Is there a playbook to sticking in a dockerhub login somewhere?

**Comment by buggtb** [comment]
this might actually not be a thing cause i have random older workspace, so i'll close this, just stuck on #18 now

**Comment by mrsimonemms** [comment]
For the record, there was always issues running with both Docker Hub and GitLab as the container registry. No one could give a good, technical reason why, but I think it's the Docker Hub limits and GitLab implements the Docker v2 API slightly differently (AWS registry is similar, but we found a workaround to that).
