### ISSUE TITLE
Workspace redirect ends up pointing at https://.ws.gitpod.spicpod.tech/

### ISSUE THREAD

**Issue by buggtb** [mrsimonemms/gitpod-self-hosted#18]
### Bug description

So i got around the docker login issue by cloning the image and just pushing it to the local repo, i think.

Cause now when I try and run stuff it tries to launch a workspace but the redirect ends up as https://.ws.gitpod.spicpod.tech/

I'm assuming the workspace is supposed to prepend it, but doesn't 

### Steps to reproduce

who knows

**Comment by buggtb** [comment]
`│ time="2023-02-16T23:26:56Z" level=error msg="error getting value: value not found for key supervisor_experimental_publicapi. Here are the available keys: "                                                                                                                                                                                                                            ││ time="2023-02-16T23:27:06Z" level=error msg="error getting value: value not found for key supervisor_experimental_publicapi. Here are the available keys: "   `

also got a load of that going on in the workspace logs

**Comment by buggtb** [comment]
oooh this looks like it refers back to the crazy escaping stuff the other day, i'll resolve that and resolve this hopefully

**Comment by buggtb** [comment]
So the escaping stuff is resolved but those  missing keys seem to be causing problems cause workspaces are stuck on "opening workspace"

**Comment by buggtb** [comment]
I dunno could also be some weird DNS stuff, i'll come back to it in the morning.

**Comment by buggtb** [comment]
Okay well its not DNS i guess.

The workspace just hangs "Initializing content …" but I also notice in the network manager thast all the ide endpoints return 404 like: https://ide.gitpod.spicpod.tech/blobserve/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-b443118d7ef8fff4a8814e5c66cd11da3a87a211/__files__/out/vs/base/common/marshalling.js

but blobserve has no obvious errors and the ide containers don't seem to be broken

**Comment by buggtb** [comment]
oh hold on, is this another templating escaping thing 😭

**Comment by buggtb** [comment]
yes and no, that fixed the ide 404's with the config in blobstore. Stick doesn't get past initialising though

**Comment by mrsimonemms** [comment]
Can you share some code so I can look at things?

**Comment by buggtb** [comment]
no need big guy... no need!

😁

![Screenshot 2023-02-17 100546](https://user-images.githubusercontent.com/103544/219614651-11384366-8518-457d-a071-d775aa1c2bba.png)

**Comment by buggtb** [comment]
Okay, i'm off on the water for a couple of days with the kids as their dad has ignored them all half term.

I've got a couple of minor terraform bits to tidy up which i'll do on sunday or monday then toss it over to you with some keys to test.
On the flux front, it all lives in a gitpod-app like yours outputting sops encrypted secrets and writing out the template, I need to fix up that tempate issue, but that works well, I'd like to push it to one of your repos as a demo or something so if people would like to use flux or another gitops provider they could, so we should probably think how these examples can live somewhere. 

I'd also like to toss a bunch of this stuff into a howto for scaleway and flux, so i'll probably ship you a couple of long winded readme's that could end up gitbook or somewhere when its all merged in and cleaned up.

**Comment by mrsimonemms** [comment]
Great, thank you.

I've set up a `docs` branch in this repo which is connected a GitBook account (currently very empty aside from a test post).
