### ISSUE TITLE
Name the cluster context

### ISSUE THREAD

**Issue by buggtb** [mrsimonemms/gitpod-self-hosted#33]
I dunno if this is possible in k3s, probably, can we name the cluster in the kube config so that we're not merging in a bunch of "default"s all the time when we launch new clusters?

(clearly I could look this up, I'm just posting the issue for tracking)

**Comment by mrsimonemms** [comment]
Yes, we definitely can name the cluster in the context. I guess it's one of those things we could provide as a variable.

I'd question the benefit vs cost of maintaining it when you could always use something like [kubens](https://github.com/ahmetb/kubectx) to manage your Kube context, but I'd probably not stand in the way of this being added if someone were to do it.
