### ISSUE TITLE
Scaleway support

### ISSUE THREAD

**Issue by buggtb** [mrsimonemms/gitpod-self-hosted#9]
Yolo, I've got most of the terraform done for a Scaleway version into a Private VPC and stuff. Would you consider consuming it into the codebase if I gave you keys to my scaleway account to test it out in the next week or so?

**Comment by mrsimonemms** [comment]
Yes, absolutely. That would be wonderful. Thank you so much. Let me know when you're happy with me taking a look at it.

My email is simon@simonemms.com if you want to share keys with me there.

**Comment by mrsimonemms** [comment]
@buggtb I've done a bit of work today on how I think the different provider sized should work - see #10 for what I've done.

If you have thoughts/feedback/criticisms etc, I'm very keen to hear it.

**Comment by buggtb** [comment]
@mrsimonemms it looks good to me from a cursory glance. I'll sync up my code with your latest later and chuck it at the cloud and see how it goes. 

I'm also working on a Flux CD "install" for the kubernetes resources because I'm a bit wary of the installer just chucking stuff at the cluster, I'd rather keep my configs in a Git repo so I can see/adjust/manage them. So I'm working on a couple of fronts trying to get stuff ironed out.

**Comment by mrsimonemms** [comment]
@buggtb Yeah, I like the idea of a Flux CD install too.

I'm going to have a play at getting an Azure provider working too. I think it'll be a good thing to then maybe write a guide on writing a new cloud provider together. A lot of this stuff is currently in my head, so it would be good getting it written down. I'd be very keen on your thoughts on that too.

**Comment by buggtb** [comment]
Docuwhat? :)

On one of our JPL open source projects we're making good use of Gitbook's open source kindness and documenting stuff on gitbook which makes it easy to manage, maintain and for users to discover.

I would say probably a per provider readme in the repo, with some information about how it works and stuf, more technical, and then point people from the readme to an associated Gitbook page that demonstrates how to deploy Gitpod using the chosen provider in a more user friendly manner.

**Comment by mrsimonemms** [comment]
Yeah, I like Gitbook as well. That's a good shout using that.

**Comment by buggtb** [comment]
Getting close, for some reason i'm serving http on an https port via the LB which is fun, but I'm nearly there. Always fun trying to unpick someone elses code to make stuff work in your own way! :)


![Screenshot 2023-02-15 023921](https://user-images.githubusercontent.com/103544/218913459-7048a53f-e29b-4b99-a415-ccd1a34306de.png)

**Comment by buggtb** [comment]
I am understanding the SSL termination correctly arent I @mrsimonemms , the cert-manager will install certs in the required places and then should serve https traffic from the cluster? I'm not supposed to stick a cert over the front of it all am I?

**Comment by buggtb** [comment]
Urf all that and it was a load balancer wiring issue...

**Comment by mrsimonemms** [comment]
I've done a first pass at Azure support which might help you with Scaleway #11 

I managed to do it without making any real changes to the existing things, although I have made one change to the [output of the VM to include both the FQDN and just the subdomain](https://github.com/mrsimonemms/gitpod-self-hosted/commit/b5d4d3a2638628d7ffc130e3244da270e19511fc). As this gets exported from the module, it would be good to include this in your Scaleway provider.
